---
- ros_topic_name: "/joint_states"
  gz_topic_name: "/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "/base_imu"
  gz_topic_name: "/base_imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS
- ros_topic_name: "/model/biped_robot/pose"
  gz_topic_name: "/model/biped_robot/pose"
  ros_type_name: "geometry_msgs/msg/Pose"
  gz_type_name: "ignition.msgs.Pose"
  direction: GZ_TO_ROS
- ros_topic_name: "/model/biped_robot/joint/R_hip_joint/cmd_force"
  gz_topic_name: "/model/biped_robot/joint/R_hip_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/model/biped_robot/joint/R_hip2_joint/cmd_force"
  gz_topic_name: "/model/biped_robot/joint/R_hip2_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/model/biped_robot/joint/R_thigh_joint/cmd_force"
  gz_topic_name: "/model/biped_robot/joint/R_thigh_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/model/biped_robot/joint/R_calf_joint/cmd_force"
  gz_topic_name: "/model/biped_robot/joint/R_calf_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/model/biped_robot/joint/R_toe_joint/cmd_force"
  gz_topic_name: "/model/biped_robot/joint/R_toe_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/model/biped_robot/joint/L_hip_joint/cmd_force"
  gz_topic_name: "/model/biped_robot/joint/L_hip_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/model/biped_robot/joint/L_hip2_joint/cmd_force"
  gz_topic_name: "/model/biped_robot/joint/L_hip2_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/model/biped_robot/joint/L_thigh_joint/cmd_force"
  gz_topic_name: "/model/biped_robot/joint/L_thigh_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/model/biped_robot/joint/L_calf_joint/cmd_force"
  gz_topic_name: "/model/biped_robot/joint/L_calf_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/model/biped_robot/joint/L_toe_joint/cmd_force"
  gz_topic_name: "/model/biped_robot/joint/L_toe_joint/cmd_force"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "pos_L_toe_joint_state"
  gz_topic_name: "pos_L_toe_joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "pos_L_calf_joint_state"
  gz_topic_name: "pos_L_calf_joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "ignition.msgs.Model"
  direction: GZ_TO_ROS
